### ISSUE TITLE
BetterNoFail doesn't allow submission after failing and restarting (BeatSaber 1.29.1)

### ISSUE THREAD

**Issue by pasketi** [zeph-yr/PlayFirstSubmitLater#3]
When playing a song with BetterNoFail enabled, after you fail a song and restart without going through the main menu, even if you clear the map afterwards, submission is prevented by BetterNoFail.

Repro:
1. Turn on BetterNoFail
2. Start a map and fail it
3. Pause the map after failing and restart
4. Complete the map
5. Observe submission disabled message in score screen

Expected functionality:
You should be able to submit scores after a restart

**Comment by zeph-yr** [comment]
Hihi, thanks for sharing. Yes this has been a known issue and is due to BS_Utils. It's been fixed in the latest version of BS_Utils 1.12.4. It's just been uploaded, so just give it a bit to show up on Mod Assistant 😄 It will require you to upgrade to 1.30+ though.

**Comment by IkaRest** [comment]
Any plans to fix it for version 1.29.1? Sorry for sticking to this version, but it's an easy to get and easy to mod version, with a lot more mods available...
