### ISSUE TITLE
PF 2.0.0 breaking mods for BS 1.31.0

### ISSUE THREAD

**Issue by gonaik** [zeph-yr/PlayFirstSubmitLater#5]
when added playfirst 2.0.0 to BS 1.31.0 it caused all mods to be removed, game starts without mods.

before mod:
![image](https://github.com/zeph-yr/PlayFirstSubmitLater/assets/58854564/4d326230-bbf0-4b3a-85c2-85f53e9f0b56)

after mod:
![image](https://github.com/zeph-yr/PlayFirstSubmitLater/assets/58854564/cc4bcde7-a965-4f57-987b-7410c867eafa)

**Comment by zeph-yr** [comment]
Hi, thanks for bringing this up. Accidentally uploaded the version for 1.29.1 oops. The correctly labeled versions for 1.31.0 and 1.29.1 (or lower) are now in two most recent releases :)
